Fix the java.lang.NoClassDefFoundError for javax.xml.bind
1. Added the dependency for javax/xml/bind/ValidationEventLocator
2. Update the ResourceHelper to use getClassLoader() instead of getClass()